---
- name: Initialize the data dir
  command: "{{ pgha_bin_dir }}/pg_ctl initdb -D {{ pgha_data_dir | quote }}"
  args:
    creates: "{{ pgha_data_dir }}/postgresql.conf"
  become_user: postgres

- name: Disable synchronous standby
  ini_file:
    path: "{{ pgha_data_dir }}/postgresql.conf"
    section: null
    option: synchronous_standby_names
    state: absent

- name: Apply replication settings
  ini_file:
    path: "{{ pgha_data_dir }}/postgresql.conf"
    section: null
    option: "{{ item.key }}"
    value: |-
      {%  if item.value is sameas true %}
      {{    'on' }}
      {%- elif item.value is sameas false %}
      {{    'off' }}
      {%- elif item.value is string %}
      {{    item.value | quote }}
      {%- else %}
      {{    item.value }}
      {%- endif %}
  with_dict: "{{ pgha_pg_settings }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure Postgres authentication
  template:
    src: pg_hba.conf.j2
    dest: "{{ pgha_data_dir }}/pg_hba.conf"
    owner: postgres

- name: Start Postgres service
  service:
    name: "{{ pgha_service }}"
    state: started

- name: Create replication user
  postgresql_user:
    name: "{{ pgha_user.user }}"
    password: "{{ pgha_user.password }}"
    role_attr_flags: REPLICATION,LOGIN
  become_user: postgres
