---
- name: Create a base backup
  shell: "MASTER={{ pgrs_master }} {{ pgrs_slave_script }} --force"
  args:
    creates: "{{ pgrs_data_dir }}/postgresql.conf"
  become: true
  become_user: postgres
  register: base_backup
  ignore_errors: true

- name: Start Postgres service
  service:
    name: "{{ pgrs_service }}"
    state: started
  delegate_to: "{{ pgrs_master }}"
  when: base_backup.failed

- name: Create a base backup (retry)
  shell: "MASTER={{ pgrs_master }} {{ pgrs_slave_script }} --force"
  args:
    creates: "{{ pgrs_data_dir }}/postgresql.conf"
  become: true
  become_user: postgres
  when: base_backup.failed
